package br.com.product.data;

import lombok.Builder;
import lombok.Data;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;
import org.springframework.data.elasticsearch.repository.support.DynamicIndex;
import org.springframework.data.elasticsearch.repository.support.DynamicType;

import javax.validation.constraints.NotNull;

/**
 * Created by giovane.silva on 26/09/2017.
 *
 * Test with composite key, generated by HashCode
 */
@Data
@Builder
@DynamicIndex
@DynamicType
@Document(indexName = "product-configuration", type = "product-configuration", createIndex = false)
public class ProductConfiguration{

    @Id
    private String id;
    private String name;
    @NotEmpty
    private String productId;
    private Long stock;
    private Double price;

}
