package br.com.product.data;

import lombok.Builder;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;
import org.springframework.data.elasticsearch.repository.support.DynamicIndex;
import org.springframework.data.elasticsearch.repository.support.DynamicType;

import javax.validation.constraints.NotNull;
import java.util.OptionalDouble;
import java.util.OptionalLong;

/**
 * Created by giovane.silva on 26/09/2017.
 *
 * Test with composite key, generated by HashCode
 */
@Data
@Builder
@DynamicIndex
@DynamicType
@Document(indexName = "product-configuration", type = "product-configuration", createIndex = false)
public class ProductConfiguration{

    @Id
    private Long id;
    private String name;
    @NotNull
    private Product product;
    private OptionalLong stock;
    private OptionalDouble price;

}
